name: Deploy TsAndCs

on:
  push:
    branches:
      - main

jobs:
  deploys_tsAndCs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poc-action
      