name: Deploy TsAndCs

on:
  push:
    branches:
      - main
      - withPandocContainer

jobs:
  deploys_tsAndCs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown --to html5 --css omse.css --output=output/termsAndConditions.html termsAndConditions.md
      - uses: actions/upload-artifact@master
        with:
          name: termsAndConditions
          path: output
          retention-days: 1
          