name: Deploy TsAndCs

on:
  push:
    branches:
      - main

jobs:
  prepareHtmlFile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - run: |
          mkdir -p forThePortal
      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown --to html5 --css omse.css --output=forThePortal/termsAndConditions.html termsAndConditions.md
      - uses: actions/upload-artifact@master
        with:
          name: termsAndConditions
          path: forThePortal/termsAndConditions.html
          retention-days: 1

  tagAndRelease:
    needs: prepareHtmlFile
    environment:
      name: dev
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          tag_prefix: v
          create_annotated_tag: false
          default_bump: false
          dry_run: false
      - uses: actions/download-artifact@v2
        with:
          name: termsAndConditions
      - name: Commit TsAndCs changes
        uses: EndBug/add-and-commit@v6
        with:
          author_name: Philippe Brossier
          author_email: brossierp@example.com
          message: 'TsAndCs updated'
          add: 'termsAndConditions.html'
          tag: ${{ steps.tag_version.outputs.new_tag }} --force
          push: true
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
