name: Deploy TsAndCs

on:
  push:
    branches:
      - main

jobs:
  prepareHtmlFile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown --to html5 --css omse.css --output=output/termsAndConditions.html termsAndConditions.md
      - uses: actions/upload-artifact@master
        with:
          name: termsAndConditions
          path: output/termsAndConditions.html
          retention-days: 1

# In prepareVersionFile, we use secrets.KEY to demonstrate that environment-specific secrets can be accessed.
# Here, we are talking about KEY which has been defined for the dev environment at https://github.com/pilif42/githubActionPoc/settings/secrets/actions
# Down the line, we will want to replace secrets.KEY with a tag (see https://github.com/marketplace/actions/github-tag).
  prepareVersionFile:
    environment:
      name: dev
    runs-on: ubuntu-18.04
    steps:
      - shell: bash
        run: |
          echo ${{ secrets.KEY }} > version.txt
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  uploadHtmlFile:
    needs: prepareHtmlFile
    environment:
      name: dev
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: termsAndConditions
#      - uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.TSANDCS_HOST }}
#          username: ${{ secrets.TSANDCS_SSH_USER }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.KEY }}
#          source: "termsAndConditions.html"
#          target: "termsAndConditions.html"

  uploadVersionFile:
    needs: prepareVersionFile
    environment:
      name: dev
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: version
#      - uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.TSANDCS_HOST }}
#          username: ${{ secrets.TSANDCS_SSH_USER }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.KEY }}
#          source: "version.txt"
#          target: "version.txt"
