name: Deploy TsAndCs

on:
  push:
    branches:
      - main
      - withPandocContainer

jobs:
  prepareHtmlFile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown --to html5 --css omse.css --output=output/termsAndConditions.html termsAndConditions.md
      - uses: actions/upload-artifact@master
        with:
          name: termsAndConditions
          path: output/termsAndConditions.html
          retention-days: 1

  uploadHtmlFile:
    needs: prepareHtmlFile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: termsAndConditions
#      - uses: garygrossgarten/github-action-scp@release
#        with:
#          local: termsAndConditions.html
#          remote: scp/single/termsAndConditions.html
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.SSH_USER }}
#          password: ${{ secrets.PASSWORD }}
