name: Deploy TsAndCs

on:
  push:
    branches:
      - main

env:
  environment: 'dev'

jobs:
  prepareHtmlFile:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output
      - uses: docker://pandoc/latex:2.9
        with:
          args: --from markdown --to html5 --css omse.css --output=output/termsAndConditions.html termsAndConditions.md
      - uses: actions/upload-artifact@master
        with:
          name: termsAndConditions
          path: output/termsAndConditions.html
          retention-days: 1

  prepareVersionFile:
    runs-on: ubuntu-18.04
    steps:
      - shell: bash
        run: |
          echo ${{ secrets.REPO_SECRET }} > version.txt
      - uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  uploadHtmlFile:
    needs: prepareHtmlFile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: termsAndConditions
#      - uses: appleboy/scp-action@master
#        with:
#          host: ${{ env.dev.TSANDCS_HOST }}
#          username: ${{ env.dev.TSANDCS_SSH_USER }}
#          port: ${{ env.dev.PORT }}
#          key: ${{ env.dev.KEY }}
#          source: "termsAndConditions.html"
#          target: "termsAndConditions.html"

  uploadVersionFile:
    needs: prepareVersionFile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: version
#      - uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.TSANDCS_HOST }}
#          username: ${{ secrets.TSANDCS_SSH_USER }}
#          port: ${{ secrets.PORT }}
#          key: ${{ secrets.KEY }}
#          source: "version.txt"
#          target: "version.txt"
